# GitHub Actions workflow
# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions
name: Lint systemd units

# Controls when the workflow will run
on:
  push:
  pull_request:
    branches: [ "main" ]
  # Run manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install systemdlint
        run: pip install systemdlint==1.*
      - name: Lint systemd units
        run: systemdlint ./scripts/systemd/*
